baseURL = "https://dogdriip.github.io/"
languageCode = "ko-kr"
title = "Blog"
theme = "onetwothree"
disqusShortname = "dogdriip"
googleAnalytics = "UA-139133764-1"

[params]
    author = "Dogdriip"
    # github = "Dogdriip"
    navigation = ["about.md"]
    style = ""
